language: node_js

node_js:
  - '8.11.1'

script:
  - npm run lint
  - npm run lint:scss
  - npm run lint:php
  - npm run test
  - npm run build

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules # npm install, unlike npm ci, doesn't wipe node_modules
