version: '3.5'

services:
    db:
        image: mysql:5.7
        volumes:
            - ../tmp/db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: wordpress

    wordpress:
        depends_on:
          - db
        volumes:
            - ../dist:/var/www/html/wp-content/plugins/plugin-name
        image: wordpress:4.9.5-php7.0-apache
        ports:
            - 8000:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
